"""Add preview image SEO fields to DocumentFile

Revision ID: 1dc941831b5f
Revises: 477a78425631
Create Date: 2026-01-28 10:44:49.301280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc941831b5f'
down_revision = '477a78425631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_alt_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_title_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preview_caption', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.drop_column('preview_caption')
        batch_op.drop_column('preview_title_text')
        batch_op.drop_column('preview_alt_text')

    # ### end Alembic commands ###
