"""Add no_watermark to image models

Revision ID: 32d35602b211
Revises: ccc886854f9f
Create Date: 2026-01-19 15:54:07.472507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d35602b211'
down_revision = 'ccc886854f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_gallery_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_watermark', sa.Boolean(), nullable=True))

    with op.batch_alter_table('product_line_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_watermark', sa.Boolean(), nullable=True))

    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_watermark', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_column('no_watermark')

    with op.batch_alter_table('product_line_images', schema=None) as batch_op:
        batch_op.drop_column('no_watermark')

    with op.batch_alter_table('home_gallery_images', schema=None) as batch_op:
        batch_op.drop_column('no_watermark')

    # ### end Alembic commands ###
