"""Add DocumentType model and update DocumentFile

Revision ID: 477a78425631
Revises: 32d35602b211
Create Date: 2026-01-28 09:25:15.243079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477a78425631'
down_revision = '32d35602b211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('preview_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('document_type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('h1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('seo_text_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.create_foreign_key(None, 'document_types', ['document_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('seo_text_html')
        batch_op.drop_column('h1')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('document_type_id')
        batch_op.drop_column('preview_image')
        batch_op.drop_column('description')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
