"""Add hero and gallery fields to ProductLine

Revision ID: 503068e9ff2d
Revises: 505f2456b6c8
Create Date: 2026-01-17 14:11:17.354916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503068e9ff2d'
down_revision = '505f2456b6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('hero_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('gallery_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.drop_column('gallery_interval')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title')
        batch_op.drop_column('hero_image')

    # ### end Alembic commands ###
