"""Add rotation field to ServiceImage

Revision ID: 505f2456b6c8
Revises: 9b01f461a5f9
Create Date: 2026-01-14 15:36:35.223199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505f2456b6c8'
down_revision = '9b01f461a5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_column('rotation')

    # ### end Alembic commands ###
