"""Add ServiceImage model and gallery_interval

Revision ID: 9b01f461a5f9
Revises: 
Create Date: 2026-01-14 14:56:37.459072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b01f461a5f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gallery_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('gallery_interval')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###
