"""Add title_text and caption to image models

Revision ID: ccc886854f9f
Revises: 503068e9ff2d
Create Date: 2026-01-19 15:30:00.167865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccc886854f9f'
down_revision = '503068e9ff2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('home_gallery_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(length=500), nullable=True))

    with op.batch_alter_table('product_line_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(length=500), nullable=True))

    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_text', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_column('caption')
        batch_op.drop_column('title_text')

    with op.batch_alter_table('product_line_images', schema=None) as batch_op:
        batch_op.drop_column('caption')
        batch_op.drop_column('title_text')

    with op.batch_alter_table('home_gallery_images', schema=None) as batch_op:
        batch_op.drop_column('caption')
        batch_op.drop_column('title_text')

    # ### end Alembic commands ###
